### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by Stolek007** [Stolek007/ssite#2]
Необходимо сделать слайдер на главной странице в части "Портфолио".
ТЗ:
1. Слайдер должен состоять из трех фотографий.
2. Плавная анимация листания, без остановки и т.д.
3. Листать должно по одному слайдеру.
4. Необходимы стрелки вперед и назад.
5. Надписи под фото(как на шаблоне).
6. Чуть ниже кнопка ( Полное портфолио ), с border-radius: 10px;

**Comment by Simply-DJI** [comment]
Выполнено!
